name = "SFTP"
uuid = "f44f501d-421f-4286-bfa3-132bd4e9b35e"
authors = ["Peter Br√§uer <pb866.git@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
LibCURL = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"

[compat]
Downloads = "1.4.3"
LibCURL = "0.6"
Logging = "1.10"
URIs = "1.5"
julia = "1.10"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
